# Create an empty dictionary. Allow 4 friends to enter their favorite language as 
# value and use key as their names. Assume that the names are unique. 

dic={}

language=input("Enter you fav language:")
name=input("Enter you Name:")
dic.update({name:language})

language=input("Enter you fav language:")
name=input("Enter you Name:")
dic.update({name:language})

language=input("Enter you fav language:")
name=input("Enter you Name:")
dic.update({name:language})

language=input("Enter you fav language:")
name=input("Enter you Name:")
dic.update({name:language})

print(dic)